### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Asian-Studies#4]
Hero image just needs to be sized and placed, please and thank you.

**Comment by ZMcGroarty** [comment]
![hero_asianstudies-min](https://cloud.githubusercontent.com/assets/15017242/24005398/4a8a06ac-0a3f-11e7-89c9-32072d610f4e.png)

**Comment by CVE82** [comment]
Awesome thank you!

**Comment by CVE82** [comment]
Victor, can you push this image?

**Comment by pixelyunicorn** [comment]
On it

**Comment by CVE82** [comment]
I just did it Victor! Thanks!
