### ISSUE TITLE
Spacing issue on Asian Studies faculty page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Asian-Studies#5]
Temple T placeholders running together on this page http://develop.cla.temple.edu/asian-studies/faculty/

**Comment by tu-chill** [comment]
Screenshot and browser info

**Comment by CVE82** [comment]
![image](https://cloud.githubusercontent.com/assets/15130721/24007044/e29502ea-0a43-11e7-9062-28c7995dc7fe.png)

**Comment by CVE82** [comment]
Height limit will be set.
