### ISSUE TITLE
Duplicate news stories

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Asian-Studies#6]
Hey, not sure if something you're working on (or aware of) is impacting this, but a single news story is appearing three times in the news feed. ("Robert Berry '08 Never Stops Learning")

**Comment by tu-chill** [comment]
Thank you. I think this will be a  quick fix

**Comment by tu-chill** [comment]
@CVE82 we'll need to revisit other views that have multiple programs filtering. Chinese, Japanese and others that you already know about

**Comment by CVE82** [comment]
Done
